[tool.djlint]
blank_line_after_tag = "load,extends,endblock"
ignore = "H014,T003,H006,H013"
indent = 2
max_attribute_length = 80
max_blank_lines = 2
preserve_blank_lines = true
profile = "django"

[tool.isort]
profile = "black"

[tool.ruff]
ignore = [
  "ANN",
  "S105",
  "PT",
  "TRY003",
  "EM101",
  "D211",
  "D212",
  "D100",
  "D104",
  "D101"
]
output-format = "github"
select = ["ALL"]

[tool.ruff.mccabe]
max-complexity = 16
