[tool.isort]
profile = "black"

[tool.ruff]
ignore = [
  "ANN",
  "S105",
  "PT",
  "TRY003",
  "EM101",
  "D211",
  "D212",
  "D100",
  "D104",
  "D101"
]
output-format = "github"
select = ["ALL"]

[tool.ruff.mccabe]
max-complexity = 16
