[tool.djlint]
blank_line_after_tag = "load,extends,endblock"
ignore = "H014,T003,H006,H013"
indent = 2
max_attribute_length = 80
max_blank_lines = 2
preserve_blank_lines = true
profile = "django"

[tool.isort]
profile = "black"

[tool.ruff.lint]
ignore = [
  "ANN",
  "S105",
  "PT",
  "TRY003",
  "EM101",
  "D211",
  "D212",
  "D100",
  "D104",
  "D105",
  "D203",  # CONFIG: incompatible with D211
  "D101"
]
select = ["ALL"]

[tool.ruff.lint.mccabe]
max-complexity = 16

[tool.ruff.lint.per-file-ignores]
"apartmancvikov//migrations/*.py" = ["RUF012"]
