[dependency-groups]
dev = [
  { include-group = "lint" },
  { include-group = "test" }
]
lint = [
  { include-group = "pre-commit" }
]
pre-commit = [
  "prek==0.5.3"
]
test = [
  "coverage"
]

[project]
dependencies = [
  "caldav==3.3.1",
  "Django==6.1.1",
  "icalendar==7.3.0",
  "mysqlclient",
  "qrcode==8.2",
  "weblate-fonts==2026.1"
]
name = "apartmancvikov"
requires-python = ">=3.11"
version = "0"

[tool.djlint]
blank_line_after_tag = "load,extends,endblock"
ignore = "H014,T003,H006,H013,H031"
indent = 2
max_attribute_length = 80
max_blank_lines = 2
preserve_blank_lines = true
profile = "django"

[tool.isort]
profile = "black"

[tool.ruff.lint]
allowed-confusables = ["–"]
future-annotations = true
extend-safe-fixes = [
  "future-required-type-annotation",
  "typing-only-standard-library-import",
  "typing-only-third-party-import",
  "reimplemented-operator"
]
preview = true
ignore = [
  "ANN",
  "no-self-use", # TODO: Method could be a function, class method, or static method
  "hardcoded-password-string",
  "docstring-missing-exception",
  "docstring-missing-returns",
  "docstring-missing-yields",
  "PT",
  "raise-vanilla-args",
  "raw-string-in-exception",
  "blank-line-before-class",
  "multi-line-summary-first-line",
  "undocumented-public-module",
  "undocumented-public-package",
  "undocumented-magic-method",
  "incorrect-blank-line-before-class", # CONFIG: incompatible with D211
  "line-too-long", # CONFIG: using formatter
  "single-line-implicit-string-concatenation", # CONFIG: incompatible with formatter
  "COM", # CONFIG: No trailing commas
  "undocumented-public-class"
]
select = ["ALL"]

[tool.ruff.lint.flake8-copyright]
min-file-size = 2
# Copyright without a year, see https://github.com/astral-sh/ruff/issues/10062
notice-rgx = "(?i)Copyright\\s+©\\s+"

[tool.ruff.lint.mccabe]
max-complexity = 16

[tool.ruff.lint.per-file-ignores]
"apartmancvikov//migrations/*.py" = ["mutable-class-default"]
