PRICE_CURRENCY = "CZK"

STANDARD_ADULT_PRICE_CZK = 950
STANDARD_CHILD_PRICE_CZK = 550
STANDARD_INFANT_PRICE_CZK = 0

STANDARD_PAID_PRICE_MIN_CZK = STANDARD_CHILD_PRICE_CZK
STANDARD_PAID_PRICE_MAX_CZK = STANDARD_ADULT_PRICE_CZK
