# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: AGPL-3.0

"""Stable business data shared by pages, metadata, and e-mail handling."""

SITE_NAME = "Apartmán Cvikov"

CONTACT_EMAIL = "ubytovani@apartmancvikov.cz"
CONTACT_PHONE = "+420775408751"
CONTACT_PHONE_DISPLAY = "+420 775 408 751"

OPERATOR_NAME = "Petra Čihařová"
OPERATOR_ID_NUMBER = "10843116"

ADDRESS_STREET = "Nábřežní 694"
ADDRESS_POSTAL_CODE = "471 54"
ADDRESS_LOCALITY = "Cvikov"
ADDRESS_REGION = "Liberecký kraj"
ADDRESS_COUNTRY = "CZ"

MAX_GUESTS = 9

PRICE_CURRENCY = "CZK"
STANDARD_ADULT_PRICE_CZK = 950
STANDARD_CHILD_PRICE_CZK = 550
STANDARD_INFANT_PRICE_CZK = 0
STANDARD_PAID_PRICE_MIN_CZK = STANDARD_CHILD_PRICE_CZK
STANDARD_PAID_PRICE_MAX_CZK = STANDARD_ADULT_PRICE_CZK
