# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: CC0-1.0

# This file is maintained in https://github.com/WeblateOrg/meta/
name: Pre-commit check

on:
  push:
    branches-ignore:
    - renovate/**
    - weblate
  pull_request:

permissions:
  contents: read

jobs:
  pre-commit:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        persist-credentials: false
    - uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
      with:
        path: ~/.cache/prek
        key: ${{ runner.os }}-prek-${{ hashFiles('.pre-commit-config.yaml', 'uv.lock') }}
    - name: Setup Python
      uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
      with:
        python-version: 3.13 || 3.14
    - uses: astral-sh/setup-uv@bec219d24cd3e171d82865faccec33120bb574f4 # v10.1.0
      with:
        enable-cache: true
        cache-suffix: pre-commit
    - name: Install dependencies
      run: uv sync --locked --only-group pre-commit
    - name: pre-commit
      run: uv run --no-sync prek run --all-files --show-diff-on-failure
      env:
        RUFF_OUTPUT_FORMAT: github
        REUSE_OUTPUT_FORMAT: github
    - name: diff
      run: git diff
      if: always()
    - uses: pre-commit-ci/lite-action@5d6cc0eb514c891a40562a58a8e71576c5c7fb43 # v1.1.0
      if: always()
      with:
        msg: 'chore(pre-commit): apply code formatting'
