name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version:
        - '3.11'
        - '3.12'
    name: Python ${{ matrix.python-version }}

    steps:
    - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2
    - name: Cache pip
      uses: actions/cache@2b250bc32ad02700b996b496c14ac8c2840a2991 # v2.1.8
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ matrix.python-version }}-${{ hashFiles('**/requirements*.txt') }}
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@dc73133d4da04e56a135ae2246682783cc7c7cb6 # v2.2.2
      with:
        python-version: ${{ matrix.python-version }}
    - run: sudo apt-get update
    - run: sudo apt-get install -y gettext
    - name: Install pip dependencies
      run: |
        pip install --upgrade pip wheel setuptools
        pip install -r requirements.txt -r requirements-dev.txt
    - name: Compile MO files
      run: ./manage.py compilemessages
    - name: Collect static files
      run: ./manage.py collectstatic
    - name: Django checks
      run: ./manage.py check
    - name: Test with Django
      run: coverage run ./manage.py test
    - name: Coverage
      run: |
        coverage combine
        coverage xml
    - uses: codecov/codecov-action@29386c70ef20e286228c72b668a06fd0e8399192 # v1.5.2
      with:
        name: Python ${{ matrix.python-version }}
